# language: "en"

# pipeline:
# - name: "SpacyNLP"
# - name: "SpacyTokenizer"
# - name: "SpacyFeaturizer"
# - name: "CRFEntityExtractor"
# - name: "EntitySynonymMapper"
# - name: "SklearnIntentClassifier"

language: "en"

pipeline: "pretrained_embeddings_spacy"